# Generated by Django 3.2.7 on 2021-10-01 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(upload_to='data/')),
                ('upload_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
